# Site
name: "5분 쇼핑"
title: "5분 쇼핑"
description: "현재 대한민국에서 가장 HOT한 제품을 5분 안에 정리해드립니다."
logo: 'assets/images/logo1.png'
favicon: 'assets/images/logo.png'
baseurl: /5shopping
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  john:
    name: 5minuteshopping
    display_name: 5minuteshopping    
    avatar: 'assets/images/avatar1.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: pagoda1698@naver.com
    web: https://je20148.github.io/5shopping/
    description: "현재 대한민국에서 가장 Hot한 제품을 5분안에 정리해드립니다."

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
